# Generated by Django 6.0 on 2026-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('reset_password', 'Reset Password'), ('registration', 'Registration')], max_length=20),
        ),
    ]
