# Generated by Django 6.0 on 2026-01-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='price_tiers',
            field=models.JSONField(blank=True, default=dict, help_text='Pricing tiers'),
        ),
        migrations.AddField(
            model_name='screen',
            name='rows',
            field=models.IntegerField(default=10, help_text='Number of rows'),
        ),
        migrations.AddField(
            model_name='screen',
            name='seat_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Complete seat configuration'),
        ),
        migrations.AddField(
            model_name='screen',
            name='seats_per_row',
            field=models.IntegerField(default=15, help_text='Average seats per row'),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_tiers',
            field=models.JSONField(blank=True, default=dict, help_text='Pricing tiers'),
        ),
        migrations.AddField(
            model_name='venue',
            name='rows',
            field=models.IntegerField(default=8, help_text='Number of rows'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Complete seat configuration'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seats_per_row',
            field=models.IntegerField(default=20, help_text='Average seats per row'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX'), ('IMAX_3D', 'IMAX 3D'), ('DOLBY_ATMOS', 'Dolby Atmos'), ('SCREEN_X', 'ScreenX')], default='2D', help_text='2D, 3D, IMAX, 4DX, etc.', max_length=50),
        ),
    ]
