# Generated by Django 6.0 on 2026-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_screen_price_tiers_screen_rows_screen_seat_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_format',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX'), ('IMAX_3D', 'IMAX 3D'), ('DOLBY_ATMOS', 'Dolby Atmos'), ('SCREEN_X', 'ScreenX')], default='2D', help_text='Format for this specific show', max_length=20),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_type',
            field=models.CharField(blank=True, default='2D', help_text='Supported formats (comma-separated): 2D, 3D, IMAX, etc.', max_length=100),
        ),
    ]
