# Generated by Django 6.0 on 2026-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_country_state_alter_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
    ]
