# Generated by Django 6.0 on 2026-01-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_change_default_status_to_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at booking time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='row',
            field=models.CharField(blank=True, help_text='Seat row (e.g., A, B, C)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='seat_category',
            field=models.CharField(blank=True, help_text='Category from price tiers', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Seat number within row', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='booking.seat'),
        ),
        migrations.AddConstraint(
            model_name='seatbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('row__isnull', False), ('seat_number__isnull', False)), fields=('show', 'row', 'seat_number'), name='unique_show_row_seat'),
        ),
        migrations.AddConstraint(
            model_name='seatbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('seat__isnull', False)), fields=('seat', 'show'), name='unique_seat_show'),
        ),
    ]
