# Generated by Django 6.0 on 2026-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_seatbooking_unique_together_seatbooking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='display_seat_number',
            field=models.CharField(blank=True, help_text='Continuous visual seat number', max_length=5, null=True),
        ),
    ]
