# Generated by Django 6.0 on 2026-01-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_seatbooking_display_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.seatbooking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seat'),
        ),
    ]
